### ISSUE TITLE
The number of cargo jobs should account for rocksdb

### ISSUE THREAD

**Issue by petevine** [arkpar/rust-rocksdb#3]
The number of cargo jobs doesn't take the ones started by `rocksdb` into account so it can get a little intense on a system with 1 GB of RAM (3 rust cargo jobs + rocksdb starting 4 gcc compilations).
Using the `-C codegen-units` flag makes it even worse.

Even though the scenario is not unsurmountable for ZRAM memory compression but still, the slowdown is evident. That probably means any setup using actual disk swap is going to grind to a halt.

**Comment by arkpar** [comment]
Build script uses `NUM_JOBS` env variable passed down by cargo. You can override it with `MAKE_MAX_JOBS` variable. Set it to `1` to get 1 gcc compilation at a time.
I'd also suggest building with clang - it uses way less memory.
`CC=clang CXX=clang++ cargo build`

**Comment by petevine** [comment]
I mainly had those average Rpi(2,3) users in mind (ZRAM is not activated by default) but thanks for the suggestion! 
I wonder if a compromise solution, like `MAKE_MAX_JOBS = NUM_JOBS / 2` wouldn't even speed up the build for everyone.

**Comment by arkpar** [comment]
Fixed in latest parity/master. make is no longer used.

**Comment by petevine** [comment]
I'm getting ca. 50% slower results in trie benchmarks with no serious regressions elsewhere. (ARM)

Did something change in the default `CFLAGS/CXXFLAGS` or the `PORTABLE=1` presence?

**Comment by petevine** [comment]
I think `-march=armv6` is being added which previously only happened with `-march=native` (used to be the default, in absence of `PORTABLE=1`)

**Comment by arkpar** [comment]
Cross compilation is now handled by the gcc crate which generate portable code. (see https://github.com/alexcrichton/gcc-rs/blob/master/src/lib.rs#L453).
Try building parity for the armv7 toolchain

**Comment by petevine** [comment]
Soo, Rpi1 is covered now, nice! I thought it was merely about rocksdb cause the rust part is not affected and correctly uses my own flags. 
  
I'll get back to you if it turns out to be a regression after all.

**Comment by petevine** [comment]
@arkpar Yeah, that was it. However, there was still some funny stuff, like the script using `gcc-4.8` which is not the default and not symlinked anywhere.  Any idea where that came from?

**Comment by arkpar** [comment]
https://github.com/alexcrichton/gcc-rs/blob/master/src/lib.rs#L603
The script checks `CC`/`CXX` variables first and then whatever gcc/g++ binary with a matching platform name is in path, i.e. `arm-linux-gnueabihf-gcc`

**Comment by petevine** [comment]
Yes, but if `cc/c++` symlinks are present on a system with multiple gcc versions, shouldn't they take precedence? The current behaviour could lead to problems with different `libstdc++` versions being used at link/run time.

Back on topic, it seems `rocksdb-sys` always uses just one job now, even when invoked directly:

`cargo build -p rocksdb-sys -j4`

**Comment by arkpar** [comment]
Yeah, gcc crate does not support any kind of parallel compilation yet - something we'll have to live with for a while. It is mitigated somewhat by the fact that other crates are compiled in parallel when parity is building from scratch.
