### ISSUE TITLE
Double Mem usage

### ISSUE THREAD

**Issue by efealatan** [arkpar/rust-rocksdb#9]
Hello,

How can we deal with this issue where the "char* rocksdb_get()" from the c interface uses
a copy thus consuming twice the memory.

result = CopyString(tmp);

The link bellow shows it.

https://github.com/facebook/rocksdb/blob/master/db/c.cc#L719

thanks,

**Comment by arkpar** [comment]
Your values are really large enough for this to become an issue?
You'd have to extend the C interface and create a C wrapper around `std::string` and then a rust interface to that. I.e. change `DBVector` to hold a C structure that contains an `std::string` and provide a pointer inside the string data using `string::data()`

**Comment by efealatan** [comment]
Thank you for your suggestion! No its not that my values are large that this would become a bottle neck but on tight resources you need to save what ever you can=)

I have found that the Cockroachdb guys have built their own c interface gonna look into how i can find a middle ground.
